package no.nav.henvendelse

const val APPLICATION_NAME = "henvendelse-api-dialogv1"
const val SERVICEUSER_USERNAME_PROPERTY = "SERVICEUSER_USERNAME"
const val SERVICEUSER_PASSWORD_PROPERTY = "SERVICEUSER_PASSWORD"
const val SECURITY_TOKEN_SERVICE_TOKEN_URL_PROPERTY = "SECURITY_TOKEN_SERVICE_TOKEN_URL"
