---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: henvendelse-api-dialogv1
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: "{{ image }}"
  port: 8080
  webproxy: true
  secureLogs:
    enabled: true
  liveness:
    path: henvendelse-api-dialogv1/internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  prometheus:
    enabled: true
    path: henvendelse-api-dialogv1/internal/prometheus
  readiness:
    path: henvendelse-api-dialogv1/internal/isReady
    initialDelay: 50
    timeout: 1
  resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 768Mi
  ingresses:
    - https://modapp-{{ namespace }}.adeo.no/henvendelse-api-dialogv1
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvhenvendelseapidialogv1
        mountPath: /var/run/secrets/nais.io/service_user
  env:
    - name: APP_ENVIRONMENT_NAME
      value: "{{ namespace }}"
    - name: APP_VERSION
      value: "{{ version }}"
    - name: SECURITYTOKENSERVICE_URL
      value: "https://security-token-service.nais.preprod.local/rest/v1/sts/ws/samltoken"
    - name: SECURITY_TOKEN_SERVICE_TOKEN_URL
      value: "https://security-token-service.nais.preprod.local/rest/v1/sts/token"
    - name: HENVENDELSE_DIALOG_V1_URL
      value: "https://modapp-{{ namespace }}.adeo.no/henvendelse/services/domene.Virksomhet/Dialog_v1"
    - name: CXF_SECURE_LOG
      value: "enabled"
