---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: henvendelse-api-dialogv1
  namespace: teamnks
  labels:
    team: teamnks
spec:
  image: "{{ image }}"
  port: 8080
  webproxy: true
  secureLogs:
    enabled: true
  liveness:
    path: henvendelse-api-dialogv1/internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  prometheus:
    enabled: true
    path: henvendelse-api-dialogv1/internal/prometheus
  readiness:
    path: henvendelse-api-dialogv1/internal/isReady
    initialDelay: 50
    timeout: 1
  resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 768Mi
  ingresses:
    - https://app-q1.adeo.no/henvendelse-api-dialogv1
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvhenvendelsedialog
        mountPath: /var/run/secrets/nais.io/service_user
  env:
    - name: APP_ENVIRONMENT_NAME
      value: "q1"
    - name: APP_VERSION
      value: "{{ version }}"
    - name: SECURITY_TOKEN_SERVICE_DISCOVERY_URL
      value: "https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration"
    - name: SECURITY_TOKEN_SERVICE_SAML_URL
      value: "https://security-token-service.nais.preprod.local/rest/v1/sts/ws/samltoken"
    - name: SECURITY_TOKEN_SERVICE_TOKEN_URL
      value: "https://security-token-service.nais.preprod.local/rest/v1/sts/token"
    - name: SF_HENVENDELSE_URL
      value: "https://sf-henvendelse-api-proxy.dev.intern.nav.no/api"
    - name: KODEVERK_URL
      value: "https://kodeverk.nais.preprod.local/"
    - name: PDL_URL
      value: "https://pdl-api-q1.dev.intern.nav.no/graphql"
    - name: UNLEASH_API_URL
      value: "https://unleash.nais.io/api/"
    - name: CXF_SECURE_LOG
      value: "enabled"
